### PR TITLE
fix(android): robustly handle full-screen load exceptions

### LINKED ISSUE #214: Crash on Production
## Issue

Getting 6 Crashes on 1 device on production. 
Below is the stacktrace
```
Exception java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:613)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:947)
Caused by java.lang.reflect.InvocationTargetException:
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:603)
Caused by java.lang.NoSuchMethodException:
  at java.lang.Class.getMethod (Class.java:2072)
  at java.lang.Class.getMethod (Class.java:1693)
  at io.invertase.googlemobileads.ReactNativeGoogleMobileAdsAdHelper.setFullScreenContentCallback (ReactNativeGoogleMobileAdsAdHelper.kt:59)
  at io.invertase.googlemobileads.ReactNativeGoogleMobileAdsFullScreenAdModule$ReactNativeGoogleMobileAdsAdLoadCallback.onAdLoaded (ReactNativeGoogleMobileAdsFullScreenAdModule.kt:215)
  at io.invertase.googlemobileads.ReactNativeGoogleMobileAdsAppOpenModule$loadAd$1.onAdLoaded (ReactNativeGoogleMobileAdsAppOpenModule.kt:63)
  at io.invertase.googlemobileads.ReactNativeGoogleMobileAdsAppOpenModule$loadAd$1.onAdLoaded (ReactNativeGoogleMobileAdsAppOpenModule.kt:60)
  at com.google.android.gms.internal.ads.zzbca.zzd (com.google.android.gms:play-services-ads-lite@@21.0.0:2)
  at com.google.android.gms.internal.ads.zzbch.zzbI (com.google.android.gms:play-services-ads-lite@@21.0.0:11)
  at com.google.android.gms.internal.ads.zzaqw.onTransact (com.google.android.gms:play-services-ads-base@@21.0.0:3)
  at android.os.Binder.transact (Binder.java:1043)
  at aep.be (aep.java:2)
  at com.google.android.gms.ads.nonagon.slot.appopen.u.a (u.java)
  at com.google.android.gms.ads.nonagon.slot.common.p.a (p.java:2)
  at com.google.android.gms.ads.nonagon.slot.appopen.ac.h (ac.java:1)
  at com.google.android.gms.ads.nonagon.slot.appopen.interstitial.e.b (e.java:4)
  at com.google.android.gms.ads.nonagon.slot.appopen.k.b (k.java:3)
  at bot.run (bot.java:6)
  at com.google.android.gms.ads.internal.util.future.c.execute (c.java:2)
  at com.google.android.gms.ads.internal.util.future.d.execute (d.java)
  at bnk.q (bnk.java:1)
  at bnk.m (bnk.java:8)
  at bnk.f (bnk.java:2)
  at bps.run (bps.java:9)
  at bog.execute (bog.java)
  at bnk.q (bnk.java:1)
  at bnk.m (bnk.java:8)
  at bnk.c (bnk.java)
  at bnn.h (bnn.java)
  at bno.run (bno.java:13)
  at com.google.android.gms.ads.internal.util.future.c.execute (c.java:2)
  at com.google.android.gms.ads.internal.util.future.d.execute (d.java)
  at bph.execute (bph.java:1)
  at bnk.q (bnk.java:1)
  at bnk.m (bnk.java:8)
  at bnk.c (bnk.java)
  at bpr.c (bpr.java)
  at com.google.android.gms.ads.internal.util.future.j.e (j.java)
  at com.google.android.gms.ads.nonagon.ad.webview.i.a (i.java:2)
  at com.google.android.gms.ads.internal.webview.q.d (q.java:4)
  at com.google.android.gms.ads.internal.webview.q.onPageFinished (q.java:11)
  at dC0.b (dC0.java)
  at J9.handleMessage (J9.java)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:223)
  at android.app.ActivityThread.main (ActivityThread.java:7950)
```

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `admob.json`:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

```ruby
# N/A
```

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
ystem:
    OS: macOS 12.2
    CPU: (8) arm64 Apple M1
    Memory: 110.00 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.6.2 - /usr/local/bin/node
    Yarn: 1.22.11 - /opt/homebrew/bin/yarn
    npm: 7.20.3 - /opt/homebrew/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0
      System Images: android-27 | Google Play Intel x86 Atom, android-28 | Google ARM64-V8a Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-31 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_302 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Are you using `TypeScript`?**
  - `Yes - Version ^4.4.4`

</p>
</details>

---

- 👉 Check out [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

### PR DESCRIPTION
**Pull request by mikehardy**
### Description

Apparently on load of full screen ads, some devices don't have the methods we expect from the admob SDK, and an InvocationTargetException is thrown, bubbles all the way up and crashes the app.

It seems reasonable to catch it locally there, but there may be other issues during load and there really is no reason to *ever* crash with a loading issue, so with this PR:

- we now wrap the entire load sequence in a try/catch, 
- we log warn (because it represents a serious failure, but we can recover) the exception
- we transmit an error event to the JS layer

This will prevent any crashes (such as from InvocationTargetExceptions) during load, with logging and error reporting

### Related issues

Fixes #214 

### Release Summary

commit message is conventional, semantic-release should work

### Checklist

- I read the [Contributor Guide](https://github.com/invertase/react-native-google-mobile-ads/blob/main/CONTRIBUTING.md)
  and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [ ] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `__tests__e2e__`
  - [ ] `jest` tests added or updated in `__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

If you review the diff while ignoring whitespace, I believe the change will be visibly trivial

I edited the code locally to throw an "test exception" of type Exception right where the issue report #214 was throwing, to test the modification.

Now you see this in the `adb logcat` if it happens:

```

09-06 10:02:23.589 13048 13048 W RNGoogleMobileAds: Unknown error on load
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds: java.lang.Exception: test exception
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at io.invertase.googlemobileads.ReactNativeGoogleMobileAdsAdHelper.setFullScreenContentCallback(ReactNativeGoogleMobileAdsAdHelper.kt:63)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at io.invertase.googlemobileads.ReactNativeGoogleMobileAdsFullScreenAdModule$ReactNativeGoogleMobileAdsAdLoadCallback.onAdLoaded(ReactNativeGoogleMobileAdsFullScreenAdModule.kt:217)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at io.invertase.googlemobileads.ReactNativeGoogleMobileAdsInterstitialModule$loadAd$1.onAdLoaded(ReactNativeGoogleMobileAdsInterstitialModule.kt:63)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at io.invertase.googlemobileads.ReactNativeGoogleMobileAdsInterstitialModule$loadAd$1.onAdLoaded(ReactNativeGoogleMobileAdsInterstitialModule.kt:60)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.ads.internal.client.zzh.zzc(com.google.android.gms:play-services-ads-lite@@21.1.0:1)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzemf.zza(Unknown Source:2)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzeyo.zza(com.google.android.gms:play-services-ads@@21.1.0:2)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzemh.zzn(com.google.android.gms:play-services-ads@@21.1.0:2)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzdde.zza(com.google.android.gms:play-services-ads@@21.1.0:1)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzdha.run(com.google.android.gms:play-services-ads@@21.1.0:1)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzcfs.execute(com.google.android.gms:play-services-ads@@21.1.0:2)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzcfu.execute(com.google.android.gms:play-services-ads@@21.1.0:1)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzdhc.zzo(com.google.android.gms:play-services-ads@@21.1.0:4)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzddf.zzn(com.google.android.gms:play-services-ads@@21.1.0:1)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzcxx.zzW(com.google.android.gms:play-services-ads@@21.1.0:1)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzemo.zzb(com.google.android.gms:play-services-ads@@21.1.0:3)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzezn.zzb(com.google.android.gms:play-services-ads@@21.1.0:8)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzfva.run(com.google.android.gms:play-services-ads@@21.1.0:7)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzcfs.execute(com.google.android.gms:play-services-ads@@21.1.0:2)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzcfu.execute(com.google.android.gms:play-services-ads@@21.1.0:1)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzftt.zzz(com.google.android.gms:play-services-ads@@21.1.0:1)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzftt.zzy(com.google.android.gms:play-services-ads@@21.1.0:12)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzftt.zzt(com.google.android.gms:play-services-ads@@21.1.0:4)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzfvv.run(com.google.android.gms:play-services-ads@@21.1.0:2)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzfuq.execute(com.google.android.gms:play-services-ads@@21.1.0:1)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzftt.zzz(com.google.android.gms:play-services-ads@@21.1.0:1)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzftt.zzy(com.google.android.gms:play-services-ads@@21.1.0:12)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzftt.zzd(com.google.android.gms:play-services-ads@@21.1.0:2)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzfty.zzg(com.google.android.gms:play-services-ads@@21.1.0:1)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzftz.run(com.google.android.gms:play-services-ads@@21.1.0:12)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzcfs.execute(com.google.android.gms:play-services-ads@@21.1.0:2)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzcfu.execute(com.google.android.gms:play-services-ads@@21.1.0:1)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzfvn.execute(com.google.android.gms:play-services-ads@@21.1.0:1)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzftt.zzz(com.google.android.gms:play-services-ads@@21.1.0:1)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzftt.zzy(com.google.android.gms:play-services-ads@@21.1.0:12)
09-06 10:02:23.596 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzftt.zzd(com.google.android.gms:play-services-ads@@21.1.0:2)
09-06 10:02:23.598 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzfvt.zzd(com.google.android.gms:play-services-ads@@21.1.0:1)
09-06 10:02:23.598 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzcga.zzd(com.google.android.gms:play-services-ads@@21.1.0:1)
09-06 10:02:23.598 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzdtm.zza(com.google.android.gms:play-services-ads@@21.1.0:1)
09-06 10:02:23.598 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzclp.zzg(com.google.android.gms:play-services-ads@@21.1.0:6)
09-06 10:02:23.598 13048 13048 W RNGoogleMobileAds:     at com.google.android.gms.internal.ads.zzclp.onPageFinished(com.google.android.gms:play-services-ads@@21.1.0:8)
09-06 10:02:23.598 13048 13048 W RNGoogleMobileAds:     at vv0.b(chromium-TrichromeWebViewGoogle6432.apk-stable-447211487:2)
09-06 10:02:23.598 13048 13048 W RNGoogleMobileAds:     at g9.handleMessage(chromium-TrichromeWebViewGoogle6432.apk-stable-447211487:61)
09-06 10:02:23.598 13048 13048 W RNGoogleMobileAds:     at android.os.Handler.dispatchMessage(Handler.java:106)
09-06 10:02:23.598 13048 13048 W RNGoogleMobileAds:     at android.os.Looper.loopOnce(Looper.java:201)
09-06 10:02:23.598 13048 13048 W RNGoogleMobileAds:     at android.os.Looper.loop(Looper.java:288)
09-06 10:02:23.598 13048 13048 W RNGoogleMobileAds:     at android.app.ActivityThread.main(ActivityThread.java:7839)
09-06 10:02:23.598 13048 13048 W RNGoogleMobileAds:     at java.lang.reflect.Method.invoke(Native Method)
09-06 10:02:23.598 13048 13048 W RNGoogleMobileAds:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
09-06 10:02:23.598 13048 13048 W RNGoogleMobileAds:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

And you see this at the javascript layer, assuming you are catching error events and logging them, as we do in the example app where I tested:

```
09-06 10:02:23.693 13048 13116 I ReactNativeJS: android GAM interstitial ad event: error
09-06 10:02:23.702 13048 13116 I ReactNativeJS: android GAM interstitial error: [googleMobileAds/internal] test exception
```

---

Think `react-native-google-mobile-ads` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Comment by mikehardy** [comment]
> But didn't we found that the "NoSuchMethod" exception can be resovled by adding some proguard rules?

That's an excellent point, however, since R8 shrinks at build time, this crash would be a total failure on all devices, it would not be device-specific (as it appears to be)

That makes me think that changing proguard rules to tell R8 to keep things would not be a fix

If it is whole app, then yes, a proguard change would be the fix.

Either way, I think this PR is defensible, since all it does is prevent crashing in case of any sort of exception, and it does not introduce silent failures (we log things + send an error event)

I wish it really were a root cause fix but as robustness, I like it

**Comment by wjaykim** [comment]
I see. Better than crashing the app. Thank you for your explanation.

**Comment by mikehardy** [comment]
mis-diagnosed this one - possibly because of bad information the related issue, but definitely also because release mode testing had not been performed on the test app, we did have an r8 shrink problem - the reflective access style was of course confusing for proguard, and it's just easier to use concrete APIs instead of having developers add proguard rules everywhere

#244 has the fix where all the release mode testing becomes easier, and then the reflective is swapped for concrete APIs

**Pull request merged**
