### PR TITLE
test(ci): various fixes to get CI green

### PR DESCRIPTION
**Pull request by mikehardy**
Just some patches + fixes to get CI going ✅

### CODE REVIEW

**Comment by mikehardy** [comment]
think I got everything going here / all entropy reversed except jest, it fails locally for me as well

**Comment by dylancom** [comment]
Great work! Do you think you can fix the failing related to "jet"?

**Comment by mikehardy** [comment]
I don't recall seeing anything jet-related, do you mean jest?

**Comment by aybabtu1337** [comment]
Locally it fails over:
react-native-google-mobile-ads/RNGoogleMobileAdsExample/node_modules/jet/dist/TestContainer.js:168
                resultText.push(<ReactNative.View style={testContainerStyles.resultItem} key="notrun">
                                ^

    SyntaxError: Unexpected token '<'

**Comment by dylancom** [comment]
Locally it fails over:

react-native-google-mobile-ads/RNGoogleMobileAdsExample/node_modules/jet/dist/TestContainer.js:168
                resultText.push(<ReactNative.View style={testContainerStyles.resultItem} key="notrun">
                                ^

    SyntaxError: Unexpected token '<'

**Comment by mikehardy** [comment]
Took another cut at it - I'm honestly not sure what value the jest testing provides here, and I'm a huge fan of testing - just this area is pretty difficult

Anyway, in the latest push I:
- cleaned up the last (I hope) deprecation errors on an an action I forgot (linting)
- noticed the linting was totally broken so updated react-native dev-dep, forward-ported typings, fixed the lint report task etc
- cleaned up the patch-package contents generation as it had some files in there that shouldn't be in there. NOTE - the files are in there because the files section of package.json / .npmignore combination is generating a bloated npm package and that needs examination

**Comment by mikehardy** [comment]
Not sure I'll have time to complete whatever is required to fix jest and I humbly submit that this PR has enough value as is to go in, as it is definitely an incremental improvement over current situation where CI has near zero signalling value, and I'm not sure what the value of the jest tests are...

**Comment by mikehardy** [comment]
Yes! Mission Accomplished :-)

image

**Pull request merged**
