### PR TITLE
fix(android): Fixed map the commands

### PR DESCRIPTION
**Pull request by minhchienwikipedia**
### Description
Seems you guys missing to convert the commands from string to number, I just added changes to fix it and make some function triggers by command work.

### Checklist

- I read the [Contributor Guide](https://github.com/invertase/react-native-google-mobile-ads/blob/main/CONTRIBUTING.md)
  and followed the process outlined there for submitting PRs.
  - [ x] Yes
- My change supports the following platforms;
  - [x ] `Android`
  - [ ] `iOS`
- My change includes tests;
  - [ x] `e2e` tests added or updated in `__tests__e2e__`
  - [ x] `jest` tests added or updated in `__tests__`
- [ ]x I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ x] Yes
  - [ ] No

### Test Plan

---

Think `react-native-google-mobile-ads` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Comment by dylancom** [comment]
The string is already parsed to an integer so I don't understand what this fixes.
`Integer.parseInt(commandId)`

**Comment by minhchienwikipedia** [comment]
@dylancom the `commandId` is `"load", "recordManualImpression"` -> so it can't be `parseInt`, you can try to test it you will get the error. So I think you guys are missing the map command string to the command number. I had tested it and it works for me

**Comment by dylancom** [comment]
Hmm I see it's broken now in our example app.
Might be related to the new arch.

**Comment by dylancom** [comment]
I'm currently on a holiday so I don't have time to test this thoroughly on both archs. @mikehardy / others? 👀

**Comment by dylancom** [comment]
Fixed it slightly differently, since we don't need the mapping of int to string anymore.
Thanks for the report.

**Pull request closed without merging**
