### PR TITLE
refactor: Change Java to Kotlin within ReactNativeGoogleMobileAds related files

### PR DESCRIPTION
**Pull request by l2hyunwoo**
### Description

- Since react-native@73 using Kotlin is default for android module. Even if it can't bring effect to this project, most of references, documents will only support Kotlin. The conversion to Kotlin within the Android module should be done slowly, to make it easier to maintain the module in the future.

### Checklist

- I read the [Contributor Guide](https://github.com/invertase/react-native-google-mobile-ads/blob/main/CONTRIBUTING.md)
  and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [ ] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `__tests__e2e__`
  - [ ] `jest` tests added or updated in `__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

---

Think `react-native-google-mobile-ads` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Comment by DoctorJohn** [comment]
These changes actually look great! They're much easier to review by looking at the relevant commits directly. @dylancom, since I can't see the CI test results, I assume the test workflows have yet to be approved for this PR?

**Comment by dylancom** [comment]
@mikehardy Could you have a look at this?

**Review by mikehardy — APPROVED** [review]
These changes do look good - thank you @l2hyunwoo !
The file move + conversion 2-step process is the only way I'm aware of in git to preserve the history as well, which is a nice touch. That's the process followed in other repositories for the .java/.kt conversion and works well
It produces some difficulty of git bisect is used with automated testing to determine errors but that's not a common practice in this repo (if used ever?) so not a problem in my mind

+1 for merge from me @dylancom

**Pull request merged**
