### PR TITLE
chore: remove unused js code

### PR DESCRIPTION
**Pull request by DoctorJohn**
### Description

Found a bunch of dead code from rnfirebase while getting more familiar with the code base.

### Checklist

- I read the [Contributor Guide](https://github.com/invertase/react-native-google-mobile-ads/blob/main/CONTRIBUTING.md)
  and followed the process outlined there for submitting PRs.
  - [x Yes
- My change supports the following platforms;
  - [ ] `Android`
  - [ ] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `__tests__e2e__`
  - [ ] `jest` tests added or updated in `__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

I ran our js tests.
CI should be happy too.

---

Think `react-native-google-mobile-ads` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Comment by dylancom** [comment]
Nice to see more contributions! Would be great if @mikehardy could review this one as he has more knowledge about the prev package.

**Review by mikehardy — APPROVED** [review]
If the code still runs without it - works for me. Splitting this module out from the old `@react-native-firebase/admob` was done as well as possible but more with an eye towards "definitely works" then "minimal". Stated differently: this looks good to me as I don't think it would compile without the stuff deleted here if it was in use

And we've got version control if I'm wrong :-)

**Comment by mikehardy** [comment]
@dylancom I would just merge it but it has been so long since I have done a merge and release that I hesitate in case you have something in flight I would conflict with, or have ordered other work etc. But I'm +1 for merge, sure

**Pull request merged**
