### PR TITLE
fix(android): forward port onAdLoaded signature for Kotlin 1.9

### PR DESCRIPTION
**Pull request by YannickBruening**
### Description

I was unable to build this and nobody else wanted to make a PR in the issue. I hope this resolves that issue. But the change has worked for me.

This PR fixes the android build issue: ReactNativeGoogleMobileAdsFullScreenAdModule.kt 'onAdLoaded' overrides nothing

### Related issues
#511 

### Checklist

- I read the [Contributor Guide](https://github.com/invertase/react-native-google-mobile-ads/blob/main/CONTRIBUTING.md)
  and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [X] `Android`
  - [ ] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `__tests__e2e__`
  - [ ] `jest` tests added or updated in `__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [ ] No

### Test Plan

---

Think `react-native-google-mobile-ads` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Comment by YannickBruening** [comment]
If the force push should be a problem for you I have no problem with recreating the pr with another non force-pushed branch. :) 
Force was done with '--force-with-lease'

**Review by mikehardy — APPROVED** [review]
Hey there - thanks for making the PR!
I'm not bothered by a force push, I like a clean commit history as a reviewer so I personally prefer it

This looks like a good change as I commented on the original issue

I'm a little pre-occupied that it may be a breaking change that requires kotlin 1.9 but I also think just for caution we can skip the analysis and just release it as such with a release note warning like:

BREAKING CHANGE: onAdLoaded for Android changed to a Kotlin 1.9 compatible signature, this may not be compatible with kotlin 1.8 in react-native 0.73, so it may
require react-native 0.74 and kotlin 1.9 to work for you

seems prescriptive enough, and people can wait to upgrade if they like

pending compile check in CI - which may indicate it works fine on kotlin 1.8...

**Comment by mikehardy** [comment]
It passed android build with react-native 0.72 in use and kotlin 1.7.x so I'm going to call this backwards compatible! No worries about compatibility I can see then - hopefully not famous last words

**Pull request merged**
