### PR TITLE
feat(ios): minor correction for macOS builds

### PR DESCRIPTION
**Pull request by birdofpreyru**
### Description

Correct the latest lib version to pass the build for macOS (Catalyst).

### Checklist

- I read the [Contributor Guide](https://github.com/invertase/react-native-google-mobile-ads/blob/main/CONTRIBUTING.md)
  and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [ ] `Android`
  - [x] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `__tests__e2e__`
  - [ ] `jest` tests added or updated in `__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

---

Think `react-native-google-mobile-ads` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
I don't see any reason not to trust you on this one, and this is the typical way to make catalyst builds work (I'm working through the same thing in other libs at the moment too...)

**Review by mikehardy — CHANGES_REQUESTED** [review]
Oh wait - if you do this, *it never resolves*. I think you need to resolve null and make sure that the API is documented as returning null sometimes ?

**Comment by birdofpreyru** [comment]
> Oh wait - if you do this, it _never resolves_.

Yeap, this way it never resolves.

> I think you need to resolve null and make sure that the API is documented as returning null sometimes ?

Not sure... for me never resolving does not cause any issues &mdash; it indefinitely blocks some ads-related logic, but at least in my apps it does not block anything non-ads related, thus its fine. In anyway, I guess similar macOS guards we added in past also cause other functions to never resolve on macOS, thus if you wanna go this way &mdash; resolving to null or something else, then we'll need to revise the rest of the library to ensure other functions behave similarly on Catalyst.

**Comment by mikehardy** [comment]
I think not resolving is a major negative - I have had bugs logged against it in react-native-firebase and at some point we'll have to fix it, but it will be after we have forgotten what was happening and thus take longer than just doing it now while we are thinking about it.

If there are other methods that are also not resolving because of IFDEFs for platforms, fixing those would be good as well, so I'd like to do so

I recognize I'm asking for a change that you indicate doesn't matter in your app, but...I also think resolving in these situations across the whole library is really just a few minutes work so ... please 🙏 😄

**Comment by birdofpreyru** [comment]
Not stale, but no ETA when I get to do it :)

**Comment by birdofpreyru** [comment]
Not stale, but no ETA when I get to do it :)

**Pull request closed without merging**
