### PR TITLE
chore(example): update to RN 0.71.4

### PR DESCRIPTION
**Pull request by aidan-24com**
### Description

Unable to build & run the android example app due to the RN issue related to the 71 RC (https://reactnative.dev/blog/2023/01/27/71rc1-android-outage-postmortem)

### Checklist

- I read the [Contributor Guide](https://github.com/invertase/react-native-google-mobile-ads/blob/main/CONTRIBUTING.md)
  and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [x] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `__tests__e2e__`
  - [ ] `jest` tests added or updated in `__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

---

🔥

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]

**Comment by mikehardy** [comment]
Have you considered running this script instead, and proposing a PR based on it? 

https://github.com/invertase/react-native-google-mobile-ads/blob/main/refresh-example.sh

That way 1) we know the script continues to work and 2) you will be fully up to date, not just on 0.70...

**Comment by aidan-24com** [comment]
I did initially try to go to latest (0.71.4), but I ran into an error with the `EventEmitter` and decided to go the easy route which was just updating to the latest patch.

I'll give the script a run and see what pops out, but I might not have the time to invest into the upgrade

**Comment by mikehardy** [comment]
If you try it and there is an EventEmitter error (maybe already logged here? 🤔 ) just knowing that - even if you don't have the time to fix the side-error - would be useful. Obviously we should be able to run with the latest react-native 😆 so, very useful knowledge

**Comment by aidan-24com** [comment]
@mikehardy the `EventEmitter` error was due to me bumping the RN version in the main `package.json`. so it is only an issue when the main package gets bumped to RN71+. 🤔 

I've reverted the changes I made to the main `package.json` and ran the refresh script. example app works, nice little script 😄.

PS:
I did notice that the scrollview in the example app doesn't actually scroll when on a small screen device (eg iPhone 7).

After a short investigation it appears that the jet test library might be stealing the touch event from the scrollview, but I didn't have the time to go deeper.

**Comment by birdofpreyru** [comment]
It would save me some time today, had you this RN update already merged into the repo :sweat:

**Comment by aidan-24com** [comment]
@mikehardy does your approval still stand?

**Comment by birdofpreyru** [comment]
By the way, any chance you looked into Fabric support? Asking, cause that's what I wanted to look into, before realizing it first requires RN upgrade to even run example.

**Comment by aidan-24com** [comment]
No, I didn't attempt using Fabric.

I'm not sure, but I think RN-google-mobile-ads might not be compatible with Fabric/New Arch (yet) due to using `use_frameworks` for the underlying native iOS SDK from google.

see here for related info (`use_frameworks` compatibility) https://rnfirebase.io/#altering-cocoapods-to-use-frameworks

**Comment by birdofpreyru** [comment]
No, this is not a problem. I have my apps running ok with new arch , (enabled turbomodulesj, disabled fabric), while using rn-google-mobile-ads and rn-firebase. Tested the also run with enabled Fabric, just not showing anything in place of ads.

**Comment by birdofpreyru** [comment]
By the way, I finally tried`refresh-example.sh` on Mac, and it does not work for me:
image

**Comment by mikehardy** [comment]
Perhaps it requires yarn 1.x, likely it does as it is failing on a link dependency and that's some kind-of-subtle yarn stuff, I wouldn't be surprised if yarn2+ broke that, and I build it all with yarn1

I use nvm and test different versions, I think that's okay, I'd focus on yarn

This does look okay - I will merge it

**Comment by mikehardy** [comment]
> By the way, any chance you looked into Fabric support? Asking, cause that's what I wanted to look into, before realizing it first requires RN upgrade to even run example. (And then I did manual rn upgrade before seeing this pr, and Mike's comment about upgrade script 😅

I have not, sorry @birdofpreyru - react-native-firebase requires `use_frameworks` and historically that hasn't worked, which pretty much zeros my motivation until fixed. I'm semi-active in getting use_frameworks to work, so I am saying "have not really looked yet", but of course it is the future. Eventually use_frameworks will work with it and all the modules I tend will get Fabric support (hopefully via community PR, being honest - but I'll be motivated to collaborate :-) )

**Pull request merged**
