### PR TITLE
chore: rename module to react-native-google-mobile-ads

### PR DESCRIPTION
**Pull request by mikehardy**
### Description

Mainly a rename as discussed from `@invertase/react-native-google-ads` to `react-native-google-mobile-ads`

Also includes some example work to handle RN67, new `npx` behavior, and Android 12

Example works on ios and android after this change, I ...think it's good?

### Release Summary

Idea is to release this with current typescript rewrite via merge from beta to master after review

### Checklist

- I read the [Contributor Guide](https://github.com/invertase/react-native-google-ads/blob/main/CONTRIBUTING.md)
  and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [x] `iOS`
- My change includes tests;
  - [x] `e2e` tests added or updated in `__tests__e2e__`
  - [x] `jest` tests added or updated in `__tests__`
- [x] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [x] Yes
  - [ ] No

### Test Plan

Please pull the beta branch and triple check it

---

Think `react-native-admob` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Comment by mikehardy** [comment]
The patch-package CI check will fail until it's published on npmjs.com as the new package name, since I've already updated the script

**Comment by dylancom** [comment]
BannerAd fails because it tries to require: "RNGoogleAdsBannerView".
Searching on "googleads" brings up 22 results which I think still need to renamed.

**Comment by mikehardy** [comment]
> BannerAd fails because it tries to require: "RNGoogleAdsBannerView". Searching on "googleads" brings up 22 results which I think still need to renamed.

Fixed by 1) adding usage of all 3 types to example/App.tsx which made the problems obvious then 2) fixing all those and doing the search you did to verify I didn't have any more silly stale references.

**Comment by dylancom** [comment]
Amazing example app! Looking great. My only feedback would be to remove the `style={styles.testSpacing}` from banner (as it's typically full width) and use the size: `BannerAdSize.ADAPTIVE_BANNER` (which is considered as the "next generation" banner ad size).

**Review by dylancom — APPROVED** [review]

**Comment by mikehardy** [comment]
Awesome, merge looks good from the app open PR, I appreciate your taking that on, kind of a sideways step for that PR but when combined with this one a big step forward I think.

Okay then, here we go...

**Comment by mikehardy** [comment]
(note that normally I wouldn't label this "chore" as a semantic thing but I specifically don't want to bump v4 right now since it's only beta and the intention was to package this breaking change in that v4 release. Hopefully the release bot gets it all done correctly...)

**Pull request merged**
