### PR TITLE
fix(android): disable coalescing of native events

### PR DESCRIPTION
**Pull request by fredrifoUni**
### Description

Disable native event coalescing by setting canCoalesce to false. This library uses a single event definition for multiple events. If they happen almost at the same time, some events would otherwise get ignored.

### Related issues

N/A

### Release Summary

android: Fix issue where some native events may not be triggered

### Checklist

- I read the [Contributor Guide](https://github.com/invertase/react-native-google-mobile-ads/blob/main/CONTRIBUTING.md)
  and followed the process outlined there for submitting PRs.
  - [X] Yes
- My change supports the following platforms;
  - [X] `Android`
  - [ ] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `__tests__e2e__`
  - [ ] `jest` tests added or updated in `__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [X] No

### Test Plan

---

Think `react-native-google-mobile-ads` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Comment by fredrifoUni** [comment]
@mikehardy Hmm, it's possible that a similar patch is needed for iOS. We only ran into this issue on Android though.

**Comment by fredrifoUni** [comment]
@mikehardy Do you think it would be possible to have this merged in? I unfortunately do not have time to look into iOS as we are not having any issues with it.

**Comment by mikehardy** [comment]
sorry this went stale - I just scanned through the iOS stuff and I'm not sure it is necessary, RCTEvent has a base implementation that has canCoalesce return FALSE, so perhaps it doesn't coalesce by default so nothing to do
Either way, yeah, seems fine to merge. Thanks for the PR!

**Comment by fredrifoUni** [comment]
> sorry this went stale - I just scanned through the iOS stuff and I'm not sure it is necessary, RCTEvent has a base implementation that has canCoalesce return FALSE, so perhaps it doesn't coalesce by default so nothing to do Either way, yeah, seems fine to merge. Thanks for the PR!

No worries. Thank you for looking into it!

**Comment by mikehardy** [comment]
all CI passed but iOS and this doesn't touch that so I merged and hit the publish button 🚢 

cheers!

**Pull request merged**
