### PR TITLE
chore: update example app / ci workflows

### PR DESCRIPTION
**Pull request by mikehardy**
### Description

- update javascript dependencies for module
- update example
- update github workflows

### Related issues

Nothing in particular but I noticed the android CI task failed on #477 and wanted to clean things up in general to see if I could get it to go green just by having *everything* be cleaner + up to date

### Release Summary

A bunch of conventional commits, this should be a rebase merge and that should drive the release correctly with one fix commit

I titled the PR with the correct thing in case I or who ever merges this assuming it goes green in CI forgets and squash merges :-)

Very careful attention should be paid to the release process as all the semantic release components were updated

### Checklist

- I read the [Contributor Guide](https://github.com/invertase/react-native-google-mobile-ads/blob/main/CONTRIBUTING.md)
  and followed the process outlined there for submitting PRs.
  - [ ] Yes
- My change supports the following platforms;
  - [ ] `Android`
  - [ ] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `__tests__e2e__`
  - [ ] `jest` tests added or updated in `__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [ ] No

### Test Plan

Lots of local runs of the example app and refresh-example script

---

Think `react-native-google-mobile-ads` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Comment by mikehardy** [comment]
Strange - worked locally but obviously needs some work here!

**Comment by MateusAndrade** [comment]
Do you need help with this @mikehardy ?

**Comment by MateusAndrade** [comment]
> > Do you need help with this @mikehardy ?
> 
> Sure @MateusAndrade - not sure how approachable it is as a problem and hasn't been the highest of priorities but if you or someone else doesn't work through all the little errors I made then I'll certainly have to 😆 . Have at it if you want to as I won't have time to come around to it for a few days at minimum

Sure! Would it be okay to fork your/update my fork with your changes?

**Comment by mikehardy** [comment]
Yeah - literally whatever seems like it would work, as a workflow. Pretty informal here with regard to process as long as everyone tries their best (which we all do, so it works out...)

**Comment by mikehardy** [comment]
will pick this up again now that holidays are over, if no one else does. JDK21 is a viable dev platform now as well, can start qualifying that...

**Comment by mikehardy** [comment]
This no longer has anything to do with SDK updates and is purely focused on cleaning up CI + the example app.

**Comment by mikehardy** [comment]
Down to one final thing to fix, which I reproduce locally with `yarn tests:jest`:

```

    SyntaxError: /home/runner/work/react-native-google-mobile-ads/react-native-google-mobile-ads/src/ads/GoogleMobileAdsBannerViewNativeComponent.ts: 'Commands' is a reserved export and may only be used to export the result of codegenNativeCommands.
      34 | // SyntaxError "'Commands' is a reserved export and may only be used to export the result of codegenNativeCommands"
      35 | // @ts-ignore -- migration to react-native 0.73
    > 36 | export const Commands: NativeCommands = codegenNativeCommands<NativeCommands>({
         | ^
      37 |   supportedCommands: ['recordManualImpression'],
      38 | });
      39 |
```

...working on it bit by bit

**Review by MateusAndrade — APPROVED** [review]

**Comment by mikehardy** [comment]
got most of this in finally with #582 ! huzzah

**Pull request closed without merging**
