### PR TITLE
fix(ios): correctly handle utf-8 chars in ios-config.sh

### LINKED ISSUE #194: [🐛] IOS Xcode Build Error :  ios_appd_id not found,  invalid multibyte char (US-ASCII)
## Issue

I am using Expo to create my projects. I have used `expo run:ios` and `expo run:android` to test my app and it works fine.
However, things happen when i start up the Xcode and try to achieve the app.

ERROR MSG i received: `ios_appd_id key not found in react-native-google-mobile-ads key in app.json. App will crash without it.
 `

Complete Error Log is:

> info: -> RNGoogleMobileAds build script started
info: 1) Locating app.json file:
info:      (1 of 2) Searching in '/Users/user/Work/MyAppName/MyAppName' for a app.json file.
info:      app.json found at /Users/user/Work/MyAppName/MyAppName/app.json
-e:6: invalid multibyte char (US-ASCII)
-e:6: invalid multibyte char (US-ASCII)
-e:6: invalid multibyte char (US-ASCII)
-e:6: invalid multibyte char (US-ASCII)
-e:6: invalid multibyte char (US-ASCII)
-e:6: invalid multibyte char (US-ASCII)
-e:6: invalid multibyte char (US-ASCII)
-e:6: invalid multibyte char (US-ASCII)
-e:6: invalid multibyte char (US-ASCII)
-e:6: invalid multibyte char (US-ASCII)
-e:6: invalid multibyte char (US-ASCII)
-e:6: invalid multibyte char (US-ASCII)
-e:6: invalid multibyte char (US-ASCII)
-e:6: invalid multibyte char (US-ASCII)
-e:6: invalid multibyte char (US-ASCII)
-e:6: invalid multibyte char (US-ASCII)
-e:6: invalid multibyte char (US-ASCII)
-e:6: invalid multibyte char (US-ASCII)
-e:6: invalid multibyte char (US-ASCII)
-e:6: invalid multibyte char (US-ASCII)
-e:6: invalid multibyte char (US-ASCII)
-e:6: invalid multibyte char (US-ASCII)
-e:6: invalid multibyte char (US-ASCII)
-e:6: invalid multibyte char (US-ASCII)
info: 2) Injecting Info.plist entries: 
    ->  0) google_mobile_ads_json_raw string e30=
error: ios_appd_id key not found in react-native-google-mobile-ads key in app.json. App will crash without it.

And in app.json, I did put 
>   "react-native-google-mobile-ads": {
>     "android_app_id": "ca-app-pub-xxxxx~xxxxx",
>     "ios_app_id": "ca-app-pub-xxxxx~xxxxx"
>   },
outside of  "expo"

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `admob.json`:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

```ruby
# N/A
```

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

### PR DESCRIPTION
**Pull request by mikehardy**
### Description

If your app.json had an app name or displayName with UTF-8 chars, ruby was not handling it and would fail to find the ios_app_id which broke the build.

With the help of @gawa1019 and others on #194 I was finally able to reproduce this and fix it (I think)

### Related issues

Fixes #194

### Release Summary

conventional commit

### Checklist

- I read the [Contributor Guide](https://github.com/invertase/react-native-google-mobile-ads/blob/main/CONTRIBUTING.md)
  and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [ ] `Android`
  - [x] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `__tests__e2e__`
  - [ ] `jest` tests added or updated in `__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

1- Added UTF-8 chars to my app.json as per #194 failure examples
2- I had rvm installed so `mv ~.rvm ~.rvmTEMP` to make sure I was using system ruby
3- `yarn example:install && yarn example:install:pods`
3- `open RNGM*Example/ios/*.xcworkspace` to open the example workspace in Xcode (it does not reproduce in Terminal all the time...)
4- do the build

It seemed to fail for me before the change but now it works

---

Think `react-native-google-mobile-ads` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Comment by mikehardy** [comment]
Requested testers on the related issue, will merge by default in a week or so, but hopefully someone tests and it's good

**Comment by wjaykim** [comment]
Somehow I didn't use utf-8 characters for my previous apps, even though I'm Korean.😅 Great finding.

**Comment by mikehardy** [comment]
I have heard basically no feedback, but...it worked for me and I was able to reproduce the problem. Going to merge and release :shrug:

**Pull request merged**
