### PR TITLE
feat(ios, android): banner full width

### PR DESCRIPTION
**Pull request by aidan-24com**
### Description

This PR adds the ability for an ad slot to resize to the full width of the screen. On Android this prop only applies to the `AdManagerAdView`.

### Checklist

- I read the [Contributor Guide](https://github.com/invertase/react-native-google-mobile-ads/blob/main/CONTRIBUTING.md)
  and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [x] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `__tests__e2e__`
  - [ ] `jest` tests added or updated in `__tests__`
- [x] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

// TODO:

---

🔥

### CODE REVIEW

**Comment by dylancom** [comment]
Could you explain the use-case further here? As for e.g. Adaptive banners already are full-width.

**Comment by aidan-24com** [comment]
@dylancom I'm struggling to get the `INLINE_ADAPTIVE_BANNER` for GAM Ads to render "full width". Not sure what I am doing wrong. Do you have any ideas?

image

**Comment by dylancom** [comment]
@aidan-24com I have no experience with GAM ads. Maybe this PR: https://github.com/invertase/react-native-google-mobile-ads/pull/277 that got closed recently due to being stale / incomplete helps?

**Comment by aidan-24com** [comment]
@dylancom thanks for your review and suggestions, but it looks like GAM ads do not work as expected (between android and iOS) with ADAPTIVE banners or the FLUID size.

We'll abandon this PR and just keep the `fullWidth` flag in a patch.

**Pull request closed without merging**
